<?php
/**
 * Tool: Generate $files array from theme's assets/loadedFiles
 * Author: Pablo Rotem
 * Author URI: https://pablo-guides.com
 * Version: 1.1 (PHP 8.3 compatible)
 *
 * שימוש:
 * 1) לשים בקובץ: wp-content/themes/<your-theme>/generate-files-array.php
 * 2) לגלוש ל- https://your.site/wp-content/themes/<your-theme>/generate-files-array.php
 *    פרמטרים אופציונליים:
 *      ?save=1        -> ישמור פלט ל- inc/lastcourse-map.php
 *      ?keepFirst=1   -> יקבע את המיפוי של המפתח הראשון (253) לקובץ ידוע מראש
 *
 * המיפוי נוצר לפי סדר אלפביתי טבעי של הקבצים בתיקייה assets/loadedFiles/
 * ויושם בדיוק על רשימת המפתחות הקבועה (253..359 עם החריגים).
 */

declare(strict_types=1);

// ---------- תצורה ----------

// קובץ ראשון קבוע (לפי בקשתך):
$fixed_first_filename = '__heb__nkTb_efxye_-sfbdje_abjvfy.pdf';

// מפתחות מדויקים, לפי הרשימה שלך (100 פריטים)
$keys = [
  253, 254, 255, 256, 257, 258, 259,
  260, 261, 263, 262, 264, 265, 266, 267, 268, 269, 270, 271,
  272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 358,
  284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295,
  296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307,
  308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,
  320, 321, 322, 324, 335, 326, 327, 330, 329, 328, 331, 332,
  333, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346,
  347, 362, 348, 351, 352, 354, 363, 357, 359
];

// סיומות מותרות
$valid_exts = ['pdf','doc','docx'];

// האם לשמור את הפלט לקובץ inc/lastcourse-map.php ?
$save_to_file = isset($_GET['save']) && $_GET['save'] == '1';

// האם לקבע את הקובץ הראשון (253) לקובץ המפורש לעיל?
$keep_first   = isset($_GET['keepFirst']) && $_GET['keepFirst'] == '1';

// ---------- מציאת תיקיית התבנית וטעינת WP (אם אפשר) ----------

// ננסה לאתר wp-load.php מעלה עד 6 רמות
function find_wp_load(string $start): ?string {
  $dir = $start;
  for ($i = 0; $i < 6; $i++) {
    $candidate = $dir . '/wp-load.php';
    if (is_file($candidate)) return $candidate;
    $dir = dirname($dir);
  }
  return null;
}

// אם הקובץ נמצא בתוך התבנית (כמו שמומלץ), __DIR__ = תיקיית התבנית
$theme_dir = __DIR__;

// ננסה לטעון וורדפרס כדי לקבל get_stylesheet_directory() (למקרה שהקובץ איננו בתבנית)
if (!function_exists('get_stylesheet_directory')) {
  $maybe_wp_load = find_wp_load(__DIR__);
  if ($maybe_wp_load) {
    require_once $maybe_wp_load;
  }
}
if (function_exists('get_stylesheet_directory')) {
  $theme_dir = get_stylesheet_directory();
}

// נתיב תיקיית הקבצים
$loaded_dir = $theme_dir . '/assets/loadedFiles';

// ---------- בדיקות ----------

header('Content-Type: text/html; charset=utf-8');

if (!is_dir($loaded_dir)) {
  $safe = htmlspecialchars($loaded_dir, ENT_QUOTES, 'UTF-8');
  echo "⚠️ התיקייה <code>$safe</code> לא נמצאה.<br>";
  echo "וודא/י שהקובץ יושב בתיקיית התבנית <em>או</em> שוורדפרס נטענה ו- get_stylesheet_directory() מחזיר את הנתיב הנכון.<br>";
  exit;
}

// ---------- שליפת קבצים ----------

$files = scandir($loaded_dir);
$pool  = [];

// מיון טבעי (כדי שההצמדה תהיה יציבה)
natcasesort($files);

foreach ($files as $f) {
  if ($f === '.' || $f === '..') continue;
  $ext = strtolower(pathinfo($f, PATHINFO_EXTENSION));
  if (!in_array($ext, $valid_exts, true)) continue;
  $pool[] = $f;
}

// ---------- בניית המיפוי ----------

$mapping = array_fill_keys($keys, ''); // ברירת־מחדל: ריק

// אם נתבקש לשמור את הראשון — נשריין אותו למפתח הראשון במערך
if ($keep_first) {
  $first_key = $keys[0];
  $mapping[$first_key] = $fixed_first_filename;

  // נוציא אותו מהמאגר אם נמצא, כדי שלא יופיע שוב
  $ix = array_search($fixed_first_filename, $pool, true);
  if ($ix !== false) {
    array_splice($pool, $ix, 1);
  }
}

// נמפה את יתר הקבצים לפי סדר לרשימת המפתחות
$k = 0;
foreach ($keys as $key) {
  // אם כבר מולא (למשל כש-keepFirst=1) — דלג
  if ($mapping[$key] !== '') continue;
  if (!isset($pool[$k])) break;
  $mapping[$key] = $pool[$k];
  $k++;
}

// ---------- הדפסה ----------

echo "<h2 style='direction:rtl;text-align:right'>פלט \$files לשילוב ב-page-graduates-2018.php</h2>";
echo "<pre style='direction:ltr; text-align:left; background:#f7f7f7; padding:12px; border:1px solid #ddd; border-radius:6px;'>\$files = [\n";
foreach ($mapping as $key => $val) {
  $safe = addslashes($val);
  echo "  $key => '$safe',\n";
}
echo "];</pre>";

echo "<p style='direction:rtl;text-align:right'>נמצאו בסה\"כ <strong>" . count($pool) . "</strong> קבצים מתאימים בתיקייה: <code>" . htmlspecialchars($loaded_dir, ENT_QUOTES, 'UTF-8') . "</code>.</p>";

// ---------- שמירה לקובץ (אופציונלי) ----------

if ($save_to_file) {
  $inc_dir = $theme_dir . '/inc';
  if (!is_dir($inc_dir)) {
    @mkdir($inc_dir, 0755, true);
  }
  $target = $inc_dir . '/lastcourse-map.php';
  $export = "<?php\n/**\n * Auto-generated by generate-files-array.php\n * Author: Pablo Rotem (https://pablo-guides.com)\n * Date: " . date('Y-m-d H:i:s') . "\n */\nreturn " . var_export($mapping, true) . ";\n";
  $ok = @file_put_contents($target, $export);
  if ($ok === false) {
    echo "<p style='color:#b00;direction:rtl;text-align:right'>❌ לא הצלחתי לשמור את הקובץ <code>inc/lastcourse-map.php</code>. בדוק/י הרשאות כתיבה.</p>";
  } else {
    echo "<p style='color:#070;direction:rtl;text-align:right'>✅ נשמר בהצלחה: <code>" . htmlspecialchars($target, ENT_QUOTES, 'UTF-8') . "</code></p>";
  }
}

echo "<hr><p style='direction:rtl;text-align:right'>נוצר ע\"י <strong>Pablo Rotem</strong> – <a href='https://pablo-guides.com' target='_blank' rel='noopener'>pablo-guides.com</a></p>";
