<?php
/*
 * Template Name: מכתבי הוקרה
 * Description: Full hardcoded list of appreciation letters linked to File Viewer
 */

if ( ! defined( 'ABSPATH' ) ) exit; 

get_header(); 

// Configuration
$VIEWER_BASE = home_url('/file-viewer/?folder=bogrim&file=');
$ICON_URL    = get_stylesheet_directory_uri() . '/assets/designFiles/page-icon.png';
?>

<style>
    .pagespecial p.para1 { margin-bottom: 10px; }
    .pagespecial a.spanpagest { text-decoration: none; color: #333; font-size: 15px; display: block; }
    .pagespecial a.spanpagest:hover { color: #FFA801; }
    .imgspecial { display: inline-block; vertical-align: middle; margin-left: 8px; }
</style>

<div class="ie-container" dir="rtl" lang="he">
  <div class="container-fluid">
    <div class="container paddXsZ">
        <div class="col-md-12 col-sm-12 col-xs-12 paddXsZ">
            
            <div class="col-md-12 col-sm-12 col-xs-12 paddXsZ">
                <p class="page3">
                    <a href="<?php echo home_url('/'); ?>" class="page3span">דף הבית</a> &gt; מכתבי הוקרה
                </p>
                <h1 class="page3line">מכתבי הוקרה</h1>
            </div>

            <div class="col-md-12 col-sm-12 col-xs-12 pagespecial">
                <h2 class="para">מכתבי הוקרה של בוגרי הקורסים</h2>

                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement205.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המשנה לנשיא בית המשפט העליון ומבקר המדינה - כב' השופט חיים כהן ז"ל:</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement209.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר העזר משפטי "כלי עבודה עזר משפטי חשוב... וראוי"</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement207.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מינוי מומחים</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement11.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אבי שטרן - יועץ הנדסי - (מס' 1)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement12.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> חמד רבאח - מסגרות - (מס' 2)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement15.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> איתמר זמיר - יועץ הנדסי - (מס' 3)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement16.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ארז דיין - הערכת פוליסות - (מס' 4)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement17.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אשר פרוליך - מומחה לכלכלה הנדסית - (מס' 5)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement18.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> גיא גפני - פתרונות תוכנה - (מס' 6)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement19.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> גיורא נדיב - פוליגרף - (מס' 7)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement20.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> גרשון שניידר - חשמאלי - (מס' 8)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement21.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> דן שרון - מהנדס חשמל - (מס' 9)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement22.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר אברהם גולן - מרכז רפאל - (מס' 10)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement23.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר אלכס בנט - אורולוג - (מס' 11)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement24.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר ג'קי ברוך - אורטופד - (מס' 12)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement25.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר מריו ברמן - מהנדס חשמל - (מס' 13)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement26.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מירי אגסי - גרפולוגית - (מס' 14)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement27.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יהושע ענתבי - מהנדס מיזוג אויר - (מס' 15)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement28.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יוסף אלול - ראש המועצה חצור הגלילות - (מס' 16)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement29.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יוסף פנחסי - מהנדס חשמל - (מס' 17)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement31.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יחיאל חצור - מהנדס בניין - (מס' 18)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement32.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יעקב ענבר- הנדסאי חשמל - (מס' 19)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement33.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ישעיה גור - נגר - (מס' 20)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement34.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> כב' האימם עפאן פתחי - (מס' 21)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement35.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> כב' הרב אברהם גולובנציץ - (מס' 22)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement36.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> כב' הרב ברוך פכטר - (מס' 23)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement37.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> כב' הרב יוסף אלנקווה - (מס' 24)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement38.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> כב' הרב עוזי שוויצה - (מס' 25)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement39.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מוטי בוהדנה - מהנדס חשמל - (מס' 26)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement40.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ישעיה גור - נגר - (מס' 27)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement42.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מתי הוד - מהנדס בניין ואדריכל - (מס' 28)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement43.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> סופר דניאל - יועץ איטום - (מס' 29)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement44.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> סלומון כהן - ראש המועצה מיתר - (מס' 30)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement45.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> סלע נהרי - מהנדס מכונות - (מס' 31)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement46.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> עודד אמרנט - מהנדס מיזוג אויר - (מס' 32)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement47.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ענת שומכר - צילום ועריכת וידאו - (מס' 33)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement48.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פרופ' עודד אברמסקי - דיקן פקול' רפואה י-ם - (מס' 34)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement49.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פתחי עראבי - שיש חסון - (מס' 35)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement50.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> צביקה אלטר - מהנדס מכונות - (מס' 36)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement51.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רו''ח נתן יזרלביץ - (מס' 37)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement52.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רו''ח יורם שיפר - (מס' 38)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement53.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רו''ח משה פומס - (מס' 39)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement54.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רמי מרגלית - מהנדס פלסטיקה - (מס' 40)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement55.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שי הרפז - מהנדס חשמל - (מס' 41)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement56.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שמואל בורין - מהנדס מעליות - (מס' 42)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement58.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> צבי גוטפריד - יועץ בטיחות - (מס' 43)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement59.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ריטה דונסקי - אדריכלית - (מס' 44)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement60.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רוני עיני - ניקוי ותיקון שטיחים - (מס' 45)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement61.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> צביקה מה-יפית, ראש מועצת אורנית - (מס' 46)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement62.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר ברסלרמן שרה - יעוץ וטיפול משפחתי - (מס' 47)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement63.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> עו''ד ישראל שלומאי - (מס' 48)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement64.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יהושע גורא - מנכל - (מס' 49)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement104.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> דניאל שמואל תומר - בורר - (מס' 50)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement105.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מיכאל ליבנה - מהנדס מיזוג אויר - (מס' 51)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement106.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר איתן ראט - רופא עיניים - (מס' 52)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement107.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> דורון טל- פיזיקאי ומומחה ממל"ז - (מס' 53)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement108.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> דוד פאר - אינסטלטור - (מס' 54)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement109.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר יורם קרטה - רופא שיניים - (מס' 55)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement110.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מיכאל רוטשילד - מהנדס מיזוג אוויר - (מס' 56)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement111.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ברוך שמיר - אדריכל - (מס' 57)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement112.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> גד בנטל - יועץ כלכלי - (מס' 58)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement113.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ג'בארין תייסיר - מהנדס אזרחי - (מס' 59)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement114.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אריה קליין - יועץ גאוטכני וגאו- סביבתי - (מס' 60)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement115.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> סילביו הרליך - מהנדס רכב - (מס' 61)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement116.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר דוד רוט - (מס' 62)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement117.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר מייל שאול - מהנדס בניין - (מס' 63)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement118.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יחיאל חצור - מהנדס - (מס' 64)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement119.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מיכאל בלנוב ואיגור מיאסקובצקי - מהנדסים - (מס' 65)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement120.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> נחום גולדנברג - (מס' 66)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement121.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שלמה נרקיס - (מס' 67)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement122.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> סעיד א' מרג'יה - מהנדס אזרחי - (מס' 68)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement123.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר יחיאל אורן - אורטופד מנתח - (מס' 69)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement124.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר אבינועם גורדין - מנתח אורטופדי - (מס' 70)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement125.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פרופ' אריה קאופמן - מומחה לטיפולי שורש - (מס' 71)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement126.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אריה קליין - יועץ גאוטכני וגאו- סביבתי - (מס' 72)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement127.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אלון נוה - יועץ בנייה - (מס' 73)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement128.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> עמירם גוטמן - מהנדס בניין - (מס' 74)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement129.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אינג' גליק חיים - מהנדס בניין - (מס' 75)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement130.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר בילא חנין - פסיכיאטרית - (מס' 76)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement131.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יצחק ויצמן - (מס' 77)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement132.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מאיר סגל - יועץ לעבודות נגרות - (מס' 78)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement133.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> נדב פז- יועץ למו''פ ביטחוני - (מס' 79)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement134.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר יעקב גורביץ - מנתח לב וחזה - (מס' 80)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement135.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יחיאל נויפלד - (מס' 81)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement136.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר מנשה ברנע - אורטופד מנתח - (מס' 82)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement137.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פרופ' ליפא בודנר - כירורג פה ולסת - ( מס' 83)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement138.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רמי רולף - אגרונום - ( מס' 84)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement139.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מאיר שמש - מדריך בטיחות מוסמך - (מס' 85)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement140.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר ברוך סגל - רופא תעסוקתי - (מס' 86)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement141.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר יהודית שחם - רפואה תעסוקתית - (מס' 87)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement142.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> משה אברמוביץ - נגר - (מס' 88)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement143.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יהושע מצליח- רו"ח - (מס' 89)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement144.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פנינה אריאלי- גרפולוגית - (מס' 90)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement146.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> איתן אבו - שרותיי הנדסת קול - (מס' 91)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement147.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> זאב גזית - פיתוח מערכות הדרכה וחינוך - (מס' 92)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement148.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר ברוך אלעד - רפואת שינה - (מס' 93)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement149.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פרופ' אורן אברמובסקי - רופא שיניים - (מס' 94)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement150.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר איז'ק אנדרי - כירורג אורתופד - (מס' 95)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement151.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רמי קסנטיני - נגר - (מס' 96)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement152.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אינג' עמוס גורליק - (מס' 97)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement153.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> משה אברמוביץ - נגר - (מס' 98)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement154.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> צורף יצחק - מהנדס בניין - (מס' 99)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement155.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מושיק שורץ - מהנדס מערכות כיבוי - (מס' 100)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement158.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> Miriam Edelson - (מס' 101)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement159.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אבנר מורי - ראש המועצה מרחבים - (מס' 102)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement160.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אמנון יבלונסקי - יעוץ והנדסה יישומית - מע' שאיבה - (מס' 103)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement161.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר מייל שאול - מהנדס בניין - (מס' 104)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement162.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> עדילי ויסגלס - תווך נדל''ן - (מס' 105)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement163.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> סגולה אלטמן - יעוץ כלכלי - (מס' 106)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement164.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אינג' אשר סלוצקי - מהנדס חשמל - (מס' 107)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement165.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> חיים זוננשיין - מהנדס חשמל - (מס' 108)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement166.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ארנסט יעקובי- מהנדס כימיה - (מס' 109)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement167.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד''ר איתן ראט - רופא עיניים - (מס' 110)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement168.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ברכה שני - גרפולוגית - (מס' 111)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement169.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אייל רוטברט -מהנדס אזרחי - (מס' 112)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement171.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אליעזר לחמן - מסגר - (מס' 113)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement172.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> סעיד א' מרג'יה - מהנדס אזרחי - (מס' 114)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement175.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רפי דגן - שמאי - (מס' 115)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement176.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מיכל דורון - גרפולוגית - (מס' 116)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement177.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> איתן נעמן- מהנדס אזרחי - (מס' 117)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement178.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> בורין שמואל -אינג' - (מס' 118)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement179.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שניידר גרשון - חשמלאי - (מס' 119)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement180.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> חצור יחיאל - אינג' - (מס' 120)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement182.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> משעלי רונן – פרסום ושיווק - ( מס' 121)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement183.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> חיים אורן רואה חשבון – (מס' 122)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement184.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר בלן סילביו – רפואת שינה - (מס' 123)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement185.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מיכה רב – דיקאנט סטודנטים – אוניברסיטת חיפה - (מס' 124)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement186.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר קליין תרזה – המעבדה לסיווג רקמות מרכז רפואי רבין - ( מס' 125)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement187.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר אורי בנדהיים וטרינר - ( מס' 126)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement188.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר אברמוביץ – שניידר פנינה – פיסיכיאטריה - ( מס' 127)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement189.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מארון חנא – מהנדס בנין וגיאודזיה - (מס' 128)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement190.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> חאלד אבו שקרה – רואה חשבון - ( מס' 129)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement192.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רוסק דוד חשמלאי – (מס' 130)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement193.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מורד אילן - יעוץ אודיו - וידיו ממוחשבים - ( מס' 131)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement194.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> בעז ארנון הנדסה אלקטרואופטית - (מס' 132)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement195.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> דן וינשטוק מהנדס חשמל - (מס' 133)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement196.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> דב כהן מהנדס חשמל - שמאי - ( מס' 134)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement235.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ליאת ברש, דוקטורנטית - פסיכותרפיסטית וקרימינולוגית - ( מס' 135)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement236.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> עמירם גוטמן מהנדס בניין - ליקויי בנייה - (מס' 136)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement237.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אריה הירש מהנדס כימי לעורות - (מס' 137)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement239.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> נאווה דגן גרפולוגית - (מס' 138)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement240.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רוני סימן טוב - מכונאי - (מס' 139)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement241.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אריה ונגרקו, בורר ומגשר כעיסוק עיקרי - (מס' 140)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement242.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר בן-ליש אפרים, כירורג מומחה - ( מס' 141)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement243.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רון רודיטי, שמאי מקרקעין - (מס' 142)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement244.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר ליאוניד אומנסקי, סגן הפסיכיאטר המחוזי, ירושלים - ( מס' 143)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement248.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יוסי שלוסמן - ממונה בטיחות - קיבוץ משמר השרון - (מס' 144)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement247.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רון רודיטי שמאי מקרקעין - (מס 145)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement249.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פרופ' אלי איסקוב - מומחה לרפואה פיזיקלית ושיקום - ( מס' 146 )</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement250.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> קרן רווה - גרפולוגית - (מס' 147)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement251.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אברהם שפירא - ממונה בטיחות - (מס' 148)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement252.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אהרונוביץ בוריס ד"ר - נוירולוג - (מס' 149)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement204.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר מתי גולני מהנדס מערכות מידע - ( מס' 150)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement206.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ראובן וקס - מהנדס כימיה - (מס' 151)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . '__heb__mfti_hffT_dsT_zftijo.png'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר אהוד נאמן - רדיולוג - (מס' 152)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement210.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מאיר סגל - נגר - ( מס' 153)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement211.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ציון חסן - ממונה בטיחות - (מס' 154)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement212.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> עוזי דגן - מהנדס מכונות - (מס' 155)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement213.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פתחי עראבי - עבודות אבן ושיש - (מס' 156)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . '__heb__sfdd_mfti_-_nkTb_efxye.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שנידר שלמה - נגר - ( מס' 157)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement215.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר גוטליב דניאל - נויורולוג - (מס' 158)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . '__heb__esykT_exfyr.doc'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מגנוס פטר - מהנדס - ממונה בטיחות - (מס' 159)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . '__heb__enmve_001.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אבני שגיב - שמאות ריהוט - (מס' 160)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement218.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מהנדס כימי אבי טאוב - (מס' 161)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement219.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר מהנדס אייל ביקלס - (מס' 162)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement220.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אורי ארבל - ממונה בטיחות - (מס' 163)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement221.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אילן דפנאי - מהנדס רכב - (מס' 164)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement222.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אלון אפשטיין - ממונה בטיחות - (מס 165)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement223.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יחזקאל ביליק - מהנדס מים - (מס' 166)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement224.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> חיים אפשטיין - מפענח תאונות דרכים באמצעות מחשב רכב - (מס' 167)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement225.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מוטי תפילין - מונה בטיחות - (מס' 168)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement226.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ניר זיו - יועץ פרקטים ועץ - (מס' 169)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement227.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> דני טבק - שיקום מבנים - (מס' 170)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement228.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מהנדס סמיח חורי - יועץ אלומיניום - (מס' 171)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement229.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יוסף אריאל - איטום ושיקום ובניה - (מס' 172)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement230.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מהנדס תנועה ותחבורה - עדי זלינגר - (מס' 173)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement231.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ממונה בטיחות - שלמה גזית - (מס' 174)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement232.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אדריכלות נוף - מרגלית סוכוי - (מס' 175)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement233.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שלמה שנייד - נגרות - רהיטנות - (מס' 176)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement234.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> בנון משה - יועץ בטיחות - (מס' 177)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement235.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רמי קסנטיני - נגרות ייצור - (מס' 178)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement236.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שאולי מזרחי - יועץ בטיחות - ( מס' 179)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement237.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אהרון לופט - ממונה בטיחות - ( מס' 180)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement238.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> פרופ' אלי איסקוב - רפואה פיזקאלית ושיקום - (מס' 181)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement239.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אריק דהן - שמאי - (מס' 182)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement240.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> גולדשמיט ליאור - שמאי מקרקעין - (מס' מס' 183)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement241.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> דמתי יוסף - גרפולוג - ( מס' 184)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement242.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> לוי ארנון - ממונה בטיחות - (מס' 185)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement243.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> זק פיני - גרפולוג - (מס' 186)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement244.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> עמוס שירן - מהנדס בניין וביסוס - ( מס' 187)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement245.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> מיכאל שלום - רפואה סינית - (מס' 188)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement246.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ישראל צחורי - מהנדס מכונות - (מס' 189)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement247.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> און יאיר - מהנדס מכונות - (מס' 190)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement248.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> עביר חדאד - מהנדסת תחבורה - ( מס' 191)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement249.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שמואל גרנות - מהנדס חשמל - (מס' 192)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement250.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> רזי שלום - נגרות - ( מס' 193)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement251.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ד"ר שמואלי גד - אורטופד מנתח - ( מס' 194)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement252.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> בר עמית - גרפולוג - (מס' 195)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement253.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> אינג' עמירם גוטמן - מומחה כשלי בניה - ( מס' 196)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement254.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יהודה זינגר - עורך דין - ( מס' 197)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement255.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ערן בנטל - שמאי מקרקעין - (מס' 198)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement256.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> יעקב מרזוק - מהנדס בניין ושמאי מקרקעין 0 (מס' - 199)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement257.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> טייב צורי - מהנדס אזרחי - ביקורת מבנים והערכת נזקים (מס' 200)</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement258.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה - לעידוד החינוך - בית ספר "יצחק הנשיא"</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement259.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה - לעידוד החינוך - בית ספר יסודי בי"ס "מכסור" - ביר אל מכסור</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement227.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה -</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement228.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה -</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement229.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה -</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement230.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה -</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement231.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה -</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement232.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה -</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement233.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה -</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement234.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> תרומתנו לקהילה -</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement245.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> חלוקת האוגדן</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement224.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנם של שופטי בית הדין הארצי לעבודה</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement223.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר משמש כלי עזר חשוב ביותר, לדוגמא - הסנגוריה הציבורית</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement222.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות שופטי בתי הדין האזורייים לעבודה</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement221.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות דייניי העדות השונות - בתי הדין הקראיים</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement220.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות דייניי בתי הדין השרעיים למוסלמים</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement219.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים לרבות שופטי בתי משפט השלום</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement218.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים לרבות שופטי ביהמ"ש המחוזי</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement217.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים, כולל ביהמ"ש העליון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement216.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים, כולל ביהמ"ש העליון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement215.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים, כולל ביהמ"ש העליון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement214.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים, כולל ביהמ"ש העליון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement213.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים, כולל ביהמ"ש העליון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement212.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים, כולל ביהמ"ש העליון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement211.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים, כולל ביהמ"ש העליון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement210.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> המאגר הונח על שולחנות השופטים, כולל ביהמ"ש העליון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement208.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ההרצאות - בהסכמת כב' נשיא בית המשפט העליון ושר המשפטים</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement206.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> כב' השופט דן ארבל, מנהל בתי המשפט - אישר הרצאות המכון</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement204.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ועדת האתיקה - שופטים - הכרה בקיומו</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement203.gif'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> ועדת האתיקה - שופטים - הוציאה הנחיות באשר לשימוש במאגר</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement201.doc'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> שאלוני המומחים מאומתים בתצהיר בפני עו"ד לרבות העדר עבר פלילי</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement246.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> קורס עדים מומחים מוכר על ידי שלטונות הביטוח הלאומי הממנים את עלות ההשתלמות במסגרת הליך להסבה מקצוע</a></p>
                <p class="para1"><a href="<?php echo $VIEWER_BASE . 'complement238.jpg'; ?>" class="spanpagest"><img src="<?php echo $ICON_URL; ?>" class="img-responsive imgspecial" alt="icon"> כבוד מבקר המדינה ונשיא בית המשפט המחוזי בחיפה מר מיכה לינדנשטראוס הכיר בתועלת המאגר.</a></p>

            </div>
        </div>
    </div>
  </div>
</div>

<?php get_footer(); ?>