<?php
/**
 * Template Name: תקנון המכון
 * Description: Fully static page for תקנון המכון. No Loop, no DB content.
 */
if (!defined('ABSPATH')) { exit; }
get_header();
?>
<main id="main" class="site-main" role="main">

  <!-- Scoped helpers just for this page -->
  <style>
    .ix-regulations { line-height: 1.9; }
    .ix-regulations .page3 { font-size: 14px; letter-spacing:.02em; opacity:.85; margin:10px 0 6px; }
    .ix-regulations .page3line { margin-top:0; margin-bottom:22px; }
    .ix-regulations .piortl { text-align: right; }
    .ix-regulations p { margin-bottom: 12px; }
    .ix-regulations strong { font-weight: 700; }
  </style>

  <div class="container-fluid ix-regulations" dir="rtl">
    <div class="container paddXsZ">

      <div class="col-md-12 col-sm-12 col-xs-12 paddXsZ">
        <div class="col-md-12 col-sm-12 col-xs-12 paddXsZ">
          <p class="page3">
            תקנון המכון
          </p>
          <h1 class="page3line">תקנון המכון </h1>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12 pagespecial-1 paddXsZ">
          <!-- FIX: col-offset-1 -> col-sm-offset-1 -->
          <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 piortl">
            <br>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong><span style="font-family: Arial;">כללי&nbsp;</span></strong></span></p>
            <p align="RIGHT"><span style="font-family: Arial;">בכפוף לתנאים שלהלן</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">המכון הישראלי לחוות דעת מומחים ובוררים </span><span style="font-family: 'Times New Roman', serif;">(</span><span style="font-family: Arial;">להלן</span><span style="font-family: 'Times New Roman', serif;">: "</span><span style="font-family: Arial;">המכון הישראלי </span><span style="font-family: 'Times New Roman', serif;">") </span><span style="font-family: Arial;">מציע באתר</span> <span style="font-family: 'Times New Roman', serif;">www.israeli-expert.com (</span><span style="font-family: Arial;">להלן</span><span style="font-family: 'Times New Roman', serif;">: "</span><span style="font-family: Arial;">האתר</span><span style="font-family: 'Times New Roman', serif;">") </span><span style="font-family: Arial;">לכל גולש באמצעות האתר </span><span style="font-family: 'Times New Roman', serif;">(</span><span style="font-family: Arial;">להלן</span><span style="font-family: 'Times New Roman', serif;">: "</span><span style="font-family: Arial;">המשתמש</span><span style="font-family: 'Times New Roman', serif;">") </span><span style="font-family: Arial;">מידע אודות שירותי מומחי האתר </span><span style="font-family: 'Times New Roman', serif;">(</span><span style="font-family: Arial;">להלן</span><span style="font-family: 'Times New Roman', serif;">: "</span><span style="font-family: Arial;">השירות</span><span style="font-family: 'Times New Roman', serif;">").</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><strong><span style="text-decoration: underline;"><span style="font-family: Arial;">קניין רוחני</span></span></strong></p>
            <p align="RIGHT"><span style="font-family: Arial;">עפ</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">י דיני זכויות היוצרים התקפים בישראל ועל פי אמנות בין לאומיות הנוגעות בדבר מלוא זכויות היוצרים והקניין הרוחני באתר </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">לרבות בעיצובו ובכל תוכנה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">יישום</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">קוד </span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">קובץ גרפי</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">טקסט</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">חלקי טקסט</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מאגרי מידע וכל חומר אחר הכלולים בו </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">שייכים להנהלת האתר</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">אין להעתיק</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">להפיץ</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">להציג בפומבי או למסור לצד שלישי כל חלק מן הנ</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">ל בלא קבלת הסכמתה המפורשת של הנהלת האתר בכתב ומראש</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">סימני המסחר והשירות</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בין אם נרשמו ובין אם טרם נרשמו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">באתר הנם עניינו של האתר בלבד </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">או</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">במידה שפורסמו מטעמם של מפרסמים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">קניינם של המכון או מפרסמים אלה בלבד</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר כולל בין השאר מאגר מקיף וייחודי המאגד בתוכו את העדים המומחים לענפיהם השונים ואת בעלי המקצועות המשפטיים והעזר משפטיים</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">כל זכויות היוצרים והקניין הרוחני במאגר זה שייכים למכון הישראלי ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או לאתר זה בלבד </span><span style="font-family: 'Times New Roman', serif;">! </span><span style="font-family: Arial;">אין לשכפל</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">להעתיק</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לצלם</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">להקליט</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לאחסן מידע</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לשדר או לקלוט ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או לעשות שימוש בכל אמצעי </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">אלקטרוני</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">אופטי</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מכני או אחר </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">במאגר כולו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או חלקו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מקצתו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בכלל בכל חלק שהוא מן החומר שבאתר זה</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">שימוש מסחרי מכל סוג שהוא בחומר הכלול באתר זה אסור בהחלט</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">אלא ברשות מפורשת בכתב ומראש מהנהלת האתר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">המשתמש רשאי לעשות שימוש הוגן בחומר המוגן לפי הכללים הקבועים בדין</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">שימוש הוגן יכלול ציטוט סביר מתוך החומר המוגן תוך ציון המקור לציטוט בין אם הוא של האתר ובין אם הוא של גורם אחר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">אסור למשתמש לעשות בחומר המוגן כל סילוף</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">פגימה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">או שינוי אחר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או כל פעולה שיש בה משום הפחתת ערך ביחס לחומר המוגן העלולה לפגוע בכבודו או בשמו של בעל זכויות הקניין הרוחני בו</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">קישורים והפניות לאתרים ושימוש במידע המתפרסם בהם</span></p>
            <p align="RIGHT"><span style="font-family: Arial;">באתר זה נמצאים קישורים לאתרים אחרים</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">הקישורים נועדו לנוחות המשתמש בלבד</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר תנהג לפי שיקול דעתה הבלעדי והמוחלט בכל הנוגע לקישורים לאתרי אינטרנט ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או למאגרי מידע אחרים אליהם ניתן להגיע באמצעות האינדקסים המופיעים באתר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">אין בין האתר לבין האתרים אליהם ניתן להגיע באמצעות הקישורים כאמור יחסים משפטיים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מסחריים ואין לאתר שליטה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או זכות בחומר הנמצא באתרים אלה</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר אינו מתחייב כי כל הקישורים שימצאו בו יהיו תקינים ויובילו לאתרי אינטרנט פעילים</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר רשאי לשנות מעת לעת את כמות וסוג הקישורים שמופיעים באתר או להחליפם באחרים והכל לפי שיקול דעתו הבלעדי</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">אין לפרש הופעת קישורים באתר כמתן גושפנקה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">אישור</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">המלצה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">או העדפה על ידי האתר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או ע</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">י המכון הישראלי לאותם האתרים המקושרים או למפעליהם</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לרבות למסמכים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או למוצרים ולכל חומר אחר הנמצאים בהם</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר לא יהיה אחראי לכל נזק ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או הפסד</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">ישיר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או עקיף</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">שיגרם לך ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בכלל כתוצאה משימוש ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או הסתמכות על המידע המופיע באתרים המקושרים</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;"><span style="text-decoration: underline;"><strong>פורומים וקבוצות דיון</strong> </span>– מצוי בעיון מחדש </span></p>
            <p align="RIGHT"><span style="font-family: Arial;">ככל שהנהלת האתר תפתח פורומים לדיון</span><span style="font-family: 'Times New Roman', serif;">: </span><span style="font-family: Arial;">אין לפרסם בפורומים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בקבוצות הדיון מידע או פרטים שהנם בלתי חוקיים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בעלי אופן מיני בוטה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">טורדניים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מעליבים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">עוינים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מזיקים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מאיימים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">גסים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">גזעניים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">פוגעים ברגשות הציבור</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מוציאים לשון הרע</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">פוגעים בפרטיות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מהווים הפרה אחרת של החוק הישראלי ואשר יש בהם כדי להוות בסיס לעבירה פלילית או עילה לתביעה אזרחית</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר או גורם מוסמך אחר שקיבל אישור בכתב ומראש של הנהלת האתר והם בלבד</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">יהיו רשאים לפרסם במסגרת אתר זה מסרים או תכנים מסחריים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">הודעות או פרסומות מסחריות</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">אין לפרסם בפורומים או בקבוצת דיון כל מסר שיש בו כדי לפגוע בזכויות יוצרים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או כל דבר אחר שזכויות הקניין הרוחני בו אינן בידי המפרסם</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">פרסום מסר כזה יתאפשר בתנאי שנתקבל אישור לכך בכתב ומראש מאת בעל הזכויות</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">מסרים ותכנים בכלל יובאו ויפורסמו באתר בדרכים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בצורות ובאופנים שייקבעו על ידי הנהלת האתר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לפי שיקול דעתה הבלעדי</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">כאשר אתה משתמש במערכת הפורומים של האתר הנך מתיר להנהלת האתר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או למי מעובדיו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מי מטעמם להשתמש במידע שהנך מוסר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">להציגו בקבוצות הדיון ולהפכו לנגיש לכל משתמש באתר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong><span style="font-family: Arial;">פרטיות</span></strong></span></p>
            <p align="RIGHT"><span style="font-family: Arial;">סעיף זה אינו מתייחס לגולשים אלא אך ורק למומחים הנרשמים למאגר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">אין כל איסוף פרטיי מידע אודות הגולשים</span> <span style="font-family: 'Times New Roman', serif;">! </span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר רשאי להשתמש בפרטים שתמסור במהלך גלישתך באתר לרבות במידע בדבר אופן ודרך השימוש באתר ובלבד שהמידע אשר ייאסף לא יזהה אותך אישית</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">האתר רשאי לשלוח אליך מדי פעם בדואר אלקטרוני מידע עיוני או אינפורמטיבי</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong><span style="font-family: Arial;">אחריות</span></strong></span></p>
            <p align="RIGHT"><span style="font-family: Arial;">השירותים והמידע באתר ניתנים לשימוש כמות שהם</span> <span style="font-family: 'Times New Roman', serif;">(as is). </span><span style="font-family: Arial;">המידע המופיע באתר הוא כללי ואינו ניתן להתאמה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או לעיצוב לפי צרכיו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או דרישותיו של כל משתמש ומשתמש</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">לא תהיה לך כל טענה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">תביעה או דרישה כלפי המכון הישראלי לחוות דעת מומחים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מפעיליו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בעליו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מנהליו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">עובדיו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">עורכיו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">חברות המפעילות אותו </span><span style="font-family: 'Times New Roman', serif;">( </span><span style="font-family: Arial;">כולם יחד בשם כולל להלן</span><span style="font-family: 'Times New Roman', serif;">: "</span><span style="font-family: Arial;">המכון</span><span style="font-family: 'Times New Roman', serif;">" ) </span><span style="font-family: Arial;">אחריות בשל אופי השירותים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מאגרי המידע ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או פרסומים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או כל דבר אחר המתפרסם באתר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">המכון לא יישא בכל אחריות</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">ישירה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או עקיפה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">נזיקית או חוזית ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או אחרת או בכלל</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בשל השימוש במערכות האתר על מרכיביו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">במידע ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או במאגרים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בפרסומים של המומחים בו או פרסומים אחרים המצויים באתר או לכל פעולה משפטית אחרת או בכלל שתינקט בהסתמך על האמור באתר זה ע</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">י מי מאלפי המומחים המנויים בו והאחריות לבדיקת מנוי המאגר מוטלת על המשתמש בשירותיו ולא תשמע כלפי המכון טענת הסתמכות בגין מידע שפרסם המומחה באתר או הועבר באמצעות המכון לצד' ג.</span></p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת המכון ממליצה לכל משתמש לדרוש מכל מומחה תקציר קורות חייו המקצועיים בטרם חתימה על הסכם עימו</span><span style="font-family: 'Times New Roman', serif;">. </span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">השימוש בשירותים האתר ייעשה על אחריותו הבלעדית והמלאה של המשתמש</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">המידע הנמסר לפרסום באתר יהיה נגיש לכל גולשי האינטרנט</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת המכון אינה אחראית לתכנים המתפרסמים באתר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">ואף אינה מתיימרת לצנזר את המסרים ואת הפרטים שיפורסמו באתר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לפיכך לא מוטלת על המכון , האתר , מפעיליו , כל אחריות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או חבות בגין אופי המידע שיתפרסם / מתפרסם באתר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">אין האתר מתחייב כי למידע שיפורסם באתר תהא היענות</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר לא יהא אחראי לכל שימוש שייעשה על ידי צד שלישי בפרטים שיעודכנו על ידך ידי המומחה.&nbsp;</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר לא יהיה אחראי לשינויים שנעשו או יעשו בחומר המוצג ע"י המומחה, המשתמש או כל צד צד ג</span><span style="font-family: 'Times New Roman', serif;">'.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר אינו מתחייב כי שירותיו לא יופרעו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">יינתנו כסדרם או ללא הפסקות</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">יתקיימו בבטחה וללא טעויות</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">ויהיו חסינים מפני חדירה בלתי </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">מאושרת למחשבים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מפני חבלה בחומרה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בתוכנה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בקווי תקשורת של האתר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או של ספקיו</span> ו<span style="font-family: 'Times New Roman', serif;">/</span>או באתר עצמו מבכל סיבה שהיא<span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><strong><span style="text-decoration: underline;"><span style="font-family: Arial;">מבנה האתר</span></span></strong></p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר תוכל לשנות מעת לעת את מבנהו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לרבות את שירותיו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מראהו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">היקפם וזמינותם של השירותים הניתנים בו וכל היבט אחר הכרוך בהם</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לרבות סגירתו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או הקפאתו באופן זמני ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או לצמיתות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או הורדתו של האתר מהרשת באופן זמני או משיקוליה לצמיתות </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">והכל</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בלא צורך להודיע לאיש על כך מראש ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או ללא צורך לנמק את החלטתה</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">שינויים כאלה עשויים להתבצע</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בין השאר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בהתחשב במטרות ויעדי האתר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">באופי הדינמי של האינטרנט ובשינויים הטכנולוגיים והאחרים המתרחשים בעולם המודרני ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או לפי שיקול דעת אחר של הנהלת האתר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בלא כל צורך לנמק את החלטתה</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong><span style="font-family: Arial;">חבר האתר</span></strong></span></p>
            <p align="RIGHT"><span style="font-family: Arial;">החברות באתר מוגבלת לבעלי מקצועות משפטיים ועזר משפטיים בלבד</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">הנהלת האתר שומרת על זכותה לדחות רישומו של כל מועמד או להפסיק את רישומו של חבר במאגר מבלי צורך לנמק את סיבת הדחייה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או הפסקת הרישום</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT"><span style="text-decoration: underline;">&nbsp;</span></p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong><span style="font-family: Arial;">דמי עדכון שנתיים</span></strong></span></p>
            <p align="RIGHT"><span style="font-family: Arial;">דמי העדכון השנתיים יחויבו מראש בראשית כל שנה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או במועד אחר שיקבע ע</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">י הנהלת האתר</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">הנהלת האתר שומרת על זכותה להעלות את מחיר דמי העדכון השנתיים מעת לעת בהתאם לצורך</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">בכל מקרה של עליה עד </span><span style="font-family: 'Times New Roman', serif;">25% </span><span style="font-family: Arial;">תהא הנהלת האתר פטורה מלפנות למומחה לשם קבלת אישורו לחיוב דמי העדכון</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">מומחה המבקש להיגרע מהמאגר חייב להודיע על רצונו לעשות כן לא יאוחר מיום </span><span style="font-family: 'Times New Roman', serif;">30/11 </span><span style="font-family: Arial;">של כל שנה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">הרשמת המומחה לאתר מהווה הסכמה מראש לתנאי זה</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong><span style="font-family: Arial;">דף אישי</span></strong></span></p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר ע</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">פ בחירתה ושיקול דעתה הבלעדי רשאית לבחור לאשר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או לפסול ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או להימנע מלאשר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או לפסול את המידע והתכנים שהעלה חבר המכון על הכתב והמובאים בדף האישי</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">דף פרטים נוספים</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">פרופיל אישי</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong><span style="font-family: Arial;">הפסקת הפעילות</span></strong></span></p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר שומרת על זכותה לפעול ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או לחדול מלפעול בכל עת ובכל דרך הנראית לה וזאת מבלי לנמק את החלטותיה בפני כל גוף ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או משתמש ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בכלל</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><strong><span style="text-decoration: underline;"><span style="font-family: Arial;">פניות</span></span></strong></p>
            <p align="RIGHT"><span style="font-family: Arial;">בכל שאלה אודות שירות זה ובשאלות נוספות הנוגעות למערכת המידע באתר ניתן לפנות באמצעות הדואר האלקטרוני לכתובת</span>
              <a href="mailto:info@israeli-expert.com">info@israeli-expert.com</a> .
            </p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><strong><span style="text-decoration: underline;"><span style="font-family: Arial;">הסתמכות על תכנים ותוצאות השימוש במידע</span></span></strong></p>
            <p align="RIGHT"><span style="font-family: Arial;">המשתמשים באתר מתבקשים להתייחס בזהירות ובביקורתיות למידע שמתפרסם באתר המכון הישראלי לחוות דעת מומחים</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">דברים אלה יפים בעיקר לדף המידע המשלים אודות המומחה או בכלל כל מידע מקצועי</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">כדוגמת תשובות לשאלות משפטיות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או דוגמאות לכתבי בי </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">דין ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או דוגמאות טפסים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מאמרים המתפרסמים באתר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או הגדרת מעמדם של המומחים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לכשאלה יופיעו בעתיד </span><span style="font-family: 'Times New Roman', serif;">(</span><span style="font-family: Arial;">אם יופיעו</span><span style="font-family: 'Times New Roman', serif;">).</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">מאמרים המתפרסמים באתר משקפים את דעת מחבריהם בלבד ואין הם מהווים ייעוץ משפטי ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או ייעוץ אחר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">כל מקרה חייב למצוא את פתרונו במסגרת המתאימה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">לפי נסיבותיו הקונקרטיות של נושא המחלוקת המונחת בבסיסו</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מפעיליו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או עובדיו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או מי מטעמם לא יישאו באחריות למידע ולתכנים שיתפרסמו באתר עצמו או לכל תוצאה שתנבע מהסתמכות עליהם או משימוש בהם</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">כל פרט שיש בו כדי לשנות זכויות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או חובות משפטיות מחייב אימות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או התייחסות מקצועית ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או חיווי</span><span style="font-family: 'Times New Roman', serif;">-</span><span style="font-family: Arial;">דעת מטעם בעל מקצוע או מומחה בתחום המתאים</span> <span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">דוגמאות הטפסים או כתבי בי דין שיוצגו באתר אינם מתיימרים להיות שלמים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או עדכניים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או להופיע בנוסח מחייב</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">אשר יתקבל ע</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">י רשויות המדינה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או ע</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">י בתי המשפט ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או ע</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">י גופים אחרים הנוגעים בדבר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">המסמכים שיתפרסמו באתר מהווים מקור לדוגמאות כלליות ומובאים לצורכי המחשה בלבד</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר ממליצה להיוועץ בעורך דין או במומחה אחר בתחומו בטרם יוחלט לערוך מסמכים או למלא טפסים בהסתמך על המידע המתפרסם באתר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">אם החלטת לפעול על בסיס מידע שפורסם באתר ובפרט על המידע שנתקבל בפורומים</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">חלה עליך האחריות המלאה והבלעדית לפעולתך</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">תוצאותיה והשלכותיה</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">במידה ותתגלה סתירה או אי התאמה בין חומר המתפרסם באתר לבין חומר המופיע בפרסומים הרשמיים בכתב של מדינת ישראל</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">חזקה על המכון כי רק החומר המופיע בפרסומים הרשמיים של מדינת ישראל ייחשב כנכון</span><span style="font-family: 'Times New Roman', serif;">, </span>אלא אם כן<span style="font-family: 'Times New Roman', serif;">, </span>טוען המכון פורשות כי הפרסום מטעם המדינה מוטעה או מטעה<span style="font-family: 'Times New Roman', serif;">. </span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">האתר עשוי לכלול מאגר מידע מקיף וייחודי המורכב מעדים מומחים לתחומיהם ומבעלי מקצועות משפטיים ועזר משפטיים</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר עושה כמיטב יכולתה לבדיקת נכונות פרטי הנרשמים ואמיתותם</span><span style="font-family: 'Times New Roman', serif;">. </span><span style="font-family: Arial;">יחד עם זאת</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">הנהלת האתר מסירה כל אחריות חוזית ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או נזיקית ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או אחרת</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">ישירה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או עקיפה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בכלל לעניין כל מידע ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או פרטים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או תכנים הנמסרים באתר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או במאגר ההתמחות המלא</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר לא תהא אחראית בכל דרך שהיא</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">באחריות ישירה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או עקיפה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בכלל לתוצאות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או השלכות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או נזקים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או הפסדים שעלולים להיגרם כתוצאה מהסתמכות על המידע שבמאגר ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או פרשנותו ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או השימוש בו בכל דרך שהיא</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">על המשתמש במאגר מוטלת אחריות מלאה ובלעדית לבדוק ולוודא את נכונות פרטי המומחים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או עורכי הדין ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או הבוררים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או המגשרים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או העדים המומחים ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או כל אדם אחר המופיע במאגר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="font-family: Arial;">הנהלת האתר לא נושאת בכל אחריות ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או חבות</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">ישירה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או עקיפה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או בכלל בגין תכני הפרסום שיימסרו על ידי הכלולים במאגר המעונינים לפרסם את כישוריהם ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או התמחויותיהם ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או טיב שירותם ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או ניסיונם</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong><span style="font-family: Arial;">תחולת דינים ושיפוט</span></strong></span></p>
            <p align="RIGHT"><span style="font-family: Arial;">בכל שימוש באתר יחולו אך ורק דיני מדינת ישראל</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מקום השיפוט הבלעדי בגין כל דבר ועניין הנובע מהסכם זה או מהאתר הנו בבתי המשפט המוסמכים במחוז חיפה</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><strong><span style="text-decoration: underline;"><span style="font-family: Arial;">הפרת תנאי שימוש</span></span></strong></p>
            <p align="RIGHT"><span style="font-family: Arial;">המשתמש ישפה את בעלי האתר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מנהליו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">עובדיו או מי מטעמם בגין כל נזק</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">הפסד</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">אבדן</span><span style="font-family: 'Times New Roman', serif;">-</span><span style="font-family: Arial;">רווח</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">תשלום או הוצאה שייגרמו להם </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">בכלל זה שכ</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">ט עו</span><span style="font-family: 'Times New Roman', serif;">"</span><span style="font-family: Arial;">ד והוצאות משפט </span><span style="font-family: 'Times New Roman', serif;">- </span><span style="font-family: Arial;">עקב הפרת תנאי שימוש אלה</span><span style="font-family: 'Times New Roman', serif;">. </span></p>
            <p align="RIGHT"><span style="font-family: Arial;">המשתמש ישפה את האתר</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">עובדיו</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">מנהליו או מי מטעמו בגין כל טענה</span><span style="font-family: 'Times New Roman', serif;">, </span><span style="font-family: Arial;">תביעה ו</span><span style="font-family: 'Times New Roman', serif;">/</span><span style="font-family: Arial;">או דרישה שתועלה נגדם על ידי גורם כלשהו כתוצאה ממידע שמסר המשתמש לפרסום באתר</span><span style="font-family: 'Times New Roman', serif;">.</span></p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><strong><span style="text-decoration: underline;">חיפוש במאגר</span></strong></p>
            <p align="RIGHT">החיפוש במאגר מוגבל ל <span style="font-family: 'Times New Roman', serif;">25&nbsp;</span>רשומות ל <span style="font-family: 'Times New Roman', serif;">24 </span>שעות<span style="font-family: 'Times New Roman', serif;">, </span>הנהלת האתר תחסום משתמש המבקש להרחיב חיפוש מעבר למספר רשומות זה .</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong>מדיניות ביטול הזמנת קורס</strong></span></p>
            <p align="RIGHT">בטול השתתפותך בהשתלמות החל מ - 14 יום לפני מועד תחילתה המשוער יחייבך בדמי בטול בסך 15%,&nbsp;<br>ובתוספת של 1% לכל יום נוסף</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><span style="text-decoration: underline;"><strong>שימוש בכרטיס אשראי או פייפאל/פרטיות</strong></span></p>
            <p align="RIGHT">ניתן לשלם עבור&nbsp;הרשמה לקורסים העזר-משפטיים שעורך המכון ו/או עבור דמי עדכון פרטים בכרטיסי אשראי או בפייפאל ON LINE, הנהלת המכון מתחייבת שלא להעביר&nbsp;את פרטי כ. האשראי לצד ג' כלשהו למעט במקרה של הוראת בית משפט.</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT">אנו מודים לכם על תשומת לב ומשוכנעים כי תפיקו את המירב.&nbsp;</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT"><strong>צוות המכון הישראלי לחוות דעת מומחים</strong></p>
            <p>&nbsp;</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT">&nbsp;</p>
            <p align="RIGHT">&nbsp;</p>

          </div>
        </div>
      </div>

    </div>
  </div>
</main>

<?php get_footer(); ?>
